/**
LER DADOS DE UM PRODUTO EM ESTOQUE - NOME, PRECO, QUANTIDADE ESTOQUE
MOSTRAR DADOS DO PRODUTO - NOME, PRECO, QUANTIDADE ESTOQUE, VOLOR TOTAL ESTOQUE
REALIZAR ENTRADA E MOSTRAR DADOS
REALIZAR SAIDA E MOSTRAR DADOS
 */

